"""new fileds in user models

Revision ID: 1902f930676a
Revises: 2b8ec67117cf
Create Date: 2019-02-19 17:46:59.514107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1902f930676a'
down_revision = '2b8ec67117cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
